apiVersion: apps/v1

kind: Deployment

metadata:

name: hello-python-deployment

labels:

app: hello-python

namespace: default

spec:

replicas: 2

selector:

matchLabels:

app: hello-python

template:

metadata:

labels:

app: hello-python

spec:

containers:

- name: hello-python

image: hello-python:latest

ports:

- containerPort: 80

---

# Nodeport service to expose the application

apiVersion: v1

kind: Service

metadata:

name: hello-python-service

namespace: default

spec:

selector:

app: hello-python

ports:

- protocol: TCP

port: 80

targetPort: 80

type: NodePort