apiVersion: apps/v1

kind: Deployment

metadata:

name: hello-python-deployment

labels:

app: hello-python

namespace: default

spec:

replicas: 1

selector:

matchLabels:

app: hello-python

template:

metadata:

labels:

app: hello-python

spec:

containers:

- name: hello-python

image: 2023mt03015/hello-python:latest

ports:

- containerPort: 80

---

apiVersion: argoproj.io/v1alpha1

kind: Rollout

metadata:

name: hello-python-rollout

namespace: default

spec:

replicas: 1

selector:

matchLabels:

app: hello-python

strategy:

blueGreen:

activeService: hello-python-service

previewService: hello-python-preview-service

autoPromotionEnabled: true

template:

metadata:

labels:

app: hello-python

spec:

containers:

- name: hello-python

image: 2023mt03015/hello-python-preview:latest

ports:

- containerPort: 80

---

apiVersion: v1

kind: Service

metadata:

name: hello-python-service

namespace: default

spec:

ports:

- protocol: TCP

port: 80

targetPort: 80

selector:

app: hello-python

---

apiVersion: v1

kind: Service

metadata:

name: hello-python-preview-service

namespace: default

spec:

ports:

- protocol: TCP

port: 80

targetPort: 80

selector:

app: hello-python