apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-python
      namespace: default
    spec:
      containers:
      - name: hello-python
        image: 2023mt03015/hello-python:latest
        ports:
        - containerPort: 5000